name: mangroves
dependencies:
  - python=3.8.5
  - matplotlib
  - numpy
  - conda-forge::earthengine-api
  - conda-forge::geemap
  - conda-forge::tensorflow
  - conda-forge::tensorboard
  - conda-forge::jupyterlab
  - setuptools
  - wheel
  - pip
  - pip:
    - tensorflow-addons
    - file:custom_packages/CustomNeuralNetworks/dist/CustomNeuralNetworks-0.1.0-py3-none-any.whl
    - file:custom_packages/eeCustomDeepTools/dist/eeCustomDeepTools-0.1.0-py3-none-any.whl
    - file:custom_packages/eeCustomTools/dist/eeCustomTools-0.1.0-py3-none-any.whl